# See https://www.chasefinch.com/nitpick-style.toml

line-length = 99
target-version = "py311"
output-format = "grouped"

[lint]
allowed-confusables = ["‘", "’", "×", "–"]
select = ["ALL"]
ignore = [
	# General configuration (see https://www.chasefinch.com/nitpick-style.toml)
	"D203", "D213", "TID252", "S101", "INT001",  # Rule conflicts
	"COM812", "ISC001", "Q000", "Q003",  # Recommended when using formatter
	"RUF100",  # Conflicts with WPS
	"ARG",  # Unused arguments often required in heirarchy
	"ERA",  # Commented-out code is OK
	"S105", "S106",  # Don't sniff for secrets
	"S311",  # Random is OK. Don't use them for "cryptographic purpses"
	"S308",  # Mark safe is OK
	"S610",  # Django "extra" is OK
	"E731", "B023",  # Lambda & unbound lambda is OK
	"B024",  # Allow ABCs without abstract methods
	"BLE001",  # Allow catching bare exception explicitly
	"FIX002", "TD003",  # Allow fully-formed TODOs

	# Specific opt-outs
	"C", "PLR09"  # Complexity rules
]

[lint.isort]
combine-as-imports = true
detect-same-package = true
section-order = [
	"future",
	"standard-library",
	"third-party",
	"django",
	"first-party",
	"local-folder"
]
known-first-party = ["google_"]
known-third-party = ["google"]
order-by-type = true

[lint.isort.sections]
django = ["django"]

[lint.per-file-ignores]
# General configuration
	# Accept imports, strings & magic numbers generated by Django. Allow Django-style migration naming. Also ignore errors (DJ01) that are enforced at the model definition.
	"*/migrations/*" = ["RUF012", "E501", "DJ01"]
	# Allow accessing private members in tests
	"tests/*" = ["SLF001"]
