"""Fetch the Software Development Axioms page from Notion.

Uses the public internal API (no auth required) and writes the result as
Markdown.
"""

from __future__ import annotations

import http.client
import json
import sys
from pathlib import Path
from typing import Any

AXIOMS_PAGE_ID = "2b020053-70de-80fa-a234-e5505babcfb1"
NOTION_HOST = "ch4se.notion.site"
NOTION_PATH = "/api/v3/loadPageChunk"

EXPECTED_ARGS = 2

HEADER = """\
<!--
  AUTO-GENERATED FILE.

  Do not edit this file by hand; instead edit the Notion page:
  https://ch4se.notion.site/Software-Development-Axioms-2b02005370de80faa234e5505babcfb1

  Then run: `make sync-docs`
-->

"""


def _post_notion(body: dict[str, Any]) -> dict[str, Any]:
    """POST JSON to the Notion internal API and return the parsed response."""
    conn = http.client.HTTPSConnection(NOTION_HOST)
    conn.request(
        "POST",
        NOTION_PATH,
        body=json.dumps(body).encode(),
        headers={
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0",
        },
    )
    resp = conn.getresponse()
    data: dict[str, Any] = json.loads(resp.read())
    conn.close()
    return data


def _fetch_blocks() -> dict[str, Any]:
    """Fetch all blocks from the public Notion page."""
    all_blocks: dict[str, Any] = {}
    cursor: dict[str, Any] = {"stack": []}

    while True:
        result = _post_notion(
            {
                "pageId": AXIOMS_PAGE_ID,
                "limit": 200,
                "cursor": cursor,
                "chunkNumber": 0,
                "verticalColumns": False,
            },
        )

        record_map = result.get("recordMap", {})
        for bid, bdata in record_map.get("block", {}).items():
            v = bdata.get("value", {}).get("value", {})
            if v.get("type"):
                all_blocks[bid] = v

        cursor = result.get("cursor", {})
        if not cursor.get("stack"):
            break

    return all_blocks


def _get_plain_text(title_array: list[list[Any]]) -> str:
    """Extract plain text from Notion rich text format.

    Each element is [text] or
    [text, [[annotation, value], ...]].
    """
    return "".join(seg[0] for seg in title_array)


def _block_to_markdown(block: dict[str, Any]) -> str:
    """Convert a single Notion block to Markdown."""
    block_type = block.get("type", "")
    props = block.get("properties", {})
    title = props.get("title", [])
    text = _get_plain_text(title) if title else ""

    if block_type == "page":
        return ""

    if block_type == "text":
        return f"{text}\n\n" if text else "\n"

    if block_type == "header":
        return f"# {text}\n\n"

    if block_type == "sub_header":
        return f"## {text}\n\n"

    if block_type == "sub_sub_header":
        return f"### {text}\n\n"

    if block_type == "bulleted_list":
        return f"- {text}\n"

    if block_type == "numbered_list":
        return f"1. {text}\n"

    if block_type == "to_do":
        checked = "x" if props.get("checked", [["No"]])[0][0] == "Yes" else " "
        return f"- [{checked}] {text}\n"

    if block_type == "code":
        language = props.get("language", [["plain text"]])[0][0]
        return f"```{language}\n{text}\n```\n\n"

    if block_type == "quote":
        return f"> {text}\n\n"

    if block_type == "divider":
        return "---\n\n"

    if block_type == "callout":
        # Handled separately in _callout_to_markdown
        return ""

    if block_type in ("table", "table_row"):
        return ""

    sys.stderr.write(
        f"Warning: Skipping unsupported block type: {block_type}\n",
    )
    return ""


def _callout_to_markdown(
    callout_block: dict[str, Any],
    blocks: dict[str, Any],
) -> str:
    """Convert a Notion callout block to a Markdown blockquote."""
    props = callout_block.get("properties", {})
    title = props.get("title", [])
    text = _get_plain_text(title) if title else ""

    fmt = callout_block.get("format", {})
    icon = fmt.get("page_icon", "")

    parts: list[str] = []
    if icon or text:
        prefix = f"{icon} " if icon else ""
        parts.append(f"{prefix}{text}")

    for child_id in callout_block.get("content", []):
        child = blocks.get(child_id)
        if not child:
            continue
        child_md = _block_to_markdown(child).rstrip("\n")
        if child_md:
            parts.append(child_md)

    body = "\n>\n> ".join(parts) if parts else ""
    return f"> {body}\n\n"


def _table_to_markdown(
    table_block: dict[str, Any],
    blocks: dict[str, Any],
) -> str:
    """Convert a Notion table block to Markdown."""
    fmt = table_block.get("format", {})
    col_order = fmt.get("table_block_column_order", [])
    has_header = fmt.get("table_block_column_header", False)
    row_ids = table_block.get("content", [])

    if not row_ids or not col_order:
        return ""

    markdown = ""
    for i, row_id in enumerate(row_ids):
        row = blocks.get(row_id, {})
        props = row.get("properties", {})
        cells = [_get_plain_text(props.get(col, [[""]])).replace("|", r"\|") for col in col_order]
        markdown += f"| {' | '.join(cells)} |\n"
        if i == 0 and has_header:
            sep = " | ".join("---" for _ in col_order)
            markdown += f"| {sep} |\n"

    return f"{markdown}\n"


def _export_axioms_md() -> str:
    """Export Axioms page from Notion to Markdown."""
    blocks = _fetch_blocks()

    page_block = blocks.get(AXIOMS_PAGE_ID, {})
    page_title = _get_plain_text(
        page_block.get("properties", {}).get("title", [["Axioms"]]),
    )
    content_ids = page_block.get("content", [])

    markdown = f"# {page_title}\n\n"

    for block_id in content_ids:
        block = blocks.get(block_id)
        if not block:
            continue
        block_type = block.get("type")
        if block_type == "table":
            markdown += _table_to_markdown(block, blocks)
        elif block_type == "callout":
            markdown += _callout_to_markdown(block, blocks)
        else:
            markdown += _block_to_markdown(block)

    return markdown


def _main() -> None:
    """Sync Axioms from Notion to a local Markdown file."""
    if len(sys.argv) != EXPECTED_ARGS:
        sys.stderr.write(
            f"Usage: {sys.argv[0]} DESTINATION_MD_PATH\n",
        )
        sys.exit(1)

    destination = Path(sys.argv[1])
    document_content = _export_axioms_md()

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        HEADER + document_content,
        encoding="utf-8",
    )

    sys.stdout.write(
        f"✓ Successfully synced Axioms to {destination}\n",
    )


if __name__ == "__main__":
    _main()
